---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  ports:
   - port: 80
  selector:
    app: ambassador
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-admin
  labels:
    service: ambassador-admin
spec:
  type: ClusterIP
  ports:
  - name: diagnostic
    port: 8877
  - name: prometheus
    port: 9102
  selector:
    service: ambassador
