apiVersion: v1
kind: Service
metadata:  
  name: idiomcentric-service
spec:
  selector:    
    app: idiomcentric-service
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
