---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: ambassador
spec:
  host: ambassador.idiomcentric.com
  prefix: /
  rewrite: /ambassador/v0/diag/
  service: ambassador-admins.ambassador:8877

