apiVersion: v1
kind: Service
metadata:  
  name: hierarchy-routes
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: hierarchy
      host: hierarchy.idiomcentric.com
      prefix: /
      service: hierarchy.hierarchy
      ---
spec:
  ports:  
  - port: 80