---
apiVersion: v1
kind: Service
metadata:  
  name: hierarchy-routes
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: hierarchy
      host: hierarchy.idiomcentric.com
      prefix: /
      service: hierarchy.hierarchy
      ---
spec:
  ports:  
  - port: 80
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: hierarchy
spec:
  External:
    auth_service: "ambassador-auth:80"
    path_prefix: "/extauth"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: hierarchy
spec:
  rules:
  - host: hierarchy.idiomcentric.com
    path: "*"
    filters:
    - name: hierarchy
      namespace: ambassador
