apiVersion: v1
kind: Service
metadata:  
  name: observe-routes
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: ops-view
      host: ops-view.paintbatch.com
      prefix: /
      service: kube-ops-view.observe
      ---
spec:
  ports:  
  - port: 80