apiVersion: v1
kind: Service
metadata:  
  name: saoirse-routes
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: saoirse
      host: saoirse.idiomcentric.com
      prefix: /
      service: saoirse.pobail
      ---
spec:
  ports:  
  - port: 80