---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-ops-view
spec:
  project: observe
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: stable/kube-ops-view
    targetRevision: 1.2.1
    helm:
      parameters:
        - name: rbac.create
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: observe
