apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantasyhub
  labels:
    app: fantasyhub
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: fantasyhub
  template:
    metadata:
      labels:
        app: fantasyhub
    spec:
      containers:
      - name: fantasyhub
        image: sevenleap/apps:fantasy-hub
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
{{ .Values.resources | toYaml | indent 10}}
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred
