---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chunk-encoder
spec:
  project: pobail
  source:
    repoURL: https://github.com/conorfennell/optimizer-k8s.git
    path: charts/chunk-encoder
  destination:
    server: https://kubernetes.default.svc
    namespace: pobail
