---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-auth
spec:
  type: ClusterIP
  ports:
    - name: http-api
      port: 80
      targetPort: http-api
  selector:
    app: ambassador-auth-httpbasic
