---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ambassador
spec:
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://github.com/conorfennell/optimizer-k8s.git
    - https://getambassador.io
  destinations:
    - server: https://kubernetes.default.svc
      namespace: ambassador
  description: "Applications that are used for ambassador"
