---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ambassador
spec:
  project: ambassador
  source:
    repoURL: https://getambassador.io
    chart: ambassador
    targetRevision: 6.6.0
    helm:
      parameters:
        - name: replicaCount
          value: '1'
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
