apiVersion: apps/v1
kind: Deployment
metadata:
  name: hierarchy
  labels:
    app: hierarchy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hierarchy
  template:
    metadata:
      labels:
        app: hierarchy
    spec:
      containers:
      - name: hierarchy
        image: sevenleap/apps:hierarchy
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
{{ .Values.resources | toYaml | indent 10}}
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        env:          
{{ .Values.env | toYaml | indent 10}}
      imagePullSecrets:
      - name: regcred
