---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-system
spec:
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: apiregistration.k8s.io
      kind: APIService
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration 
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://github.com/helm/charts.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kube-system
  description: "Applications that support kubernete operations"