---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  project: kube-system
  source:
    repoURL: https://github.com/conorfennell/optimizer-k8s.git
    path: charts/metrics-server
    targetRevision: e64f8c15918fb10b1506dd2d476a096b112286dd
    helm:
      parameters:
        - name: serviceAccount.name
          value: metrics-server
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
        - name: resources.limits.memory
          value: 300Mi
        - name: args[0]
          value: "--kubelet-preferred-address-types=InternalIP"
        - name: args[1]
          value: "--logtostderr"
        - name: args[2]
          value: "--kubelet-insecure-tls"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
