---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  project: kube-system
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/metrics-server
    targetRevision: eab3da62ec347915c58188ba6d0aa8e4db26fe89
    helm:
      parameters:
        - name: serviceAccount.name
          value: metrics-server
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
        - name: resources.limits.memory
          value: 300Mi
        - name: args[0]
          value: "--kubelet-preferred-address-types=InternalIP"
        - name: args[1]
          value: "--logtostderr"
        - name: args[2]
          value: "--kubelet-insecure-tls"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
