apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: soccer-goals-bot
  labels:
    app: soccer-goals-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccer-goals-bot
  serviceName: "soccer-goals-bot"    
  template:
    metadata:
      labels:
        app: soccer-goals-bot
    spec:
      containers:
      - name: soccer-goals-bot
        image: sevenleap/apps:soccer-goals-bot
        env:
          - name: BPL_CHAT_ID
            valueFrom:
              configMapKeyRef:
                name: soccer-goals-bot
                key: BPL_CHAT_ID
          - name: BUND_CHAT_ID
            valueFrom:
                configMapKeyRef:
                  name: soccer-goals-bot
                  key: BUND_CHAT_ID
          - name: WC_CHAT_ID
            valueFrom:
              configMapKeyRef:
                name: soccer-goals-bot
                key: WC_CHAT_ID
          - name: FIRE_BASE_ROOT
            valueFrom:
              configMapKeyRef:
                name: soccer-goals-bot
                key: FIRE_BASE_ROOT
          - name: FIRE_BASE_JSON
            valueFrom:
              configMapKeyRef:
                name: soccer-goals-bot
                key: FIRE_BASE_JSON
          - name: BOT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: soccer-goals-bot
                key: BOT_TOKEN
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
      imagePullSecrets:
      - name: regcred
