apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-argos
  labels:
    app: check-argos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-argos
  template:
    metadata:
      labels:
        app: check-argos
    spec:
      replicas: {{ .Values.replicas }}
      containers:
      - name: check-argos
        image: sevenleap/apps:check-argos
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
{{ .Values.resources | toYaml | indent 10}}
        readinessProbe:
          httpGet:
            path: /search?q=seven
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /search?q=seven
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred
