apiVersion: v1
kind: Service
metadata:  
  name: check-argos
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: check-argos
      host: checkargos.com
      prefix: /
      service: check-argos
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: check-argos-www
      host: www.checkargos.com
      prefix: /
      service: check-argos
spec:
  selector:    
    app: check-argos
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
