---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: optimize
spec:
  sourceRepos:
    - https://github.com/conorfennell/paint-batch-optimizer.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: optimize
  description: "Applications that are used for optimization"
