resources:
  requests:
    memory: "200Mi"
    cpu: 100m
  limits:
    memory: "200Mi"

replicas: 1

env:
  - name: "DB_HIERARCHY_HOSTNAME"
    value: "jdbc:postgresql://postgres-0.postgres.hierarchy:5432"
  - name: "DB_HIERARCHY_DATABASE"
    value: "postgres"
  - name: "DB_HIERARCHY_USERNAME"
    value: "username"
  - name: "DB_HIERARCHY_PASSWORD"
    value: "password"
  - name: "DB_HIERARCHY_DRIVERCLASSNAME"
    value: "org.postgresql.Driver"
