---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fantasyhub
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://github.com/conorfennell/optimizer-k8s.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: fantasyhub
  description: "Applications that are used for fast development"
